import { useState, useEffect } from "react";
import {
  BookOpen, FileText, BarChart2, Menu, X, ExternalLink,
  GraduationCap, Award, Mail, ChevronRight, Bot, Code2, Layers, Download
} from "lucide-react";

// ─── DATA LAYER ──────────────────────────────────────────────────────────────
// All content lives here. Swap this object with a fetch() from data.json.
const DATA = {
  meta: {
    name: "Shardul Kattewar",
    title: "B.Tech Student · Data Science & ML Enthusiast",
    affiliation: "RAIT (Ramrao Adik Institute of Technology)",
    tagline: "Machine Learning · Predictive Systems · Applied AI",
    email: "shardul.kattewar@example.com",
    github: "github.com/shardul",
    linkedin: "linkedin.com/in/shardul",
    cvUrl: "https://github.com/shardul",
    avatar: null,
  },

  stats: [
    { label: "Latest Academic Performance", value: "7.32", suffix: " / 10", note: "Semester 5 SGPA" },
    { label: "Cumulative CGPA", value: "6.31", suffix: " / 10", note: "Overall cumulative total" },
    { label: "CGPA Growth (Sem 1 to Sem 5)", value: "4.39 → 7.32", suffix: "", note: "Approximate rise highlighted across semesters" },
    { label: "Certification Status", value: "In Progress", suffix: "", note: "Data Science & GenAI specialization" },
  ],

  about: `I am a B.Tech student focused on practical machine learning systems and data-driven problem solving. My current work centers on predictive modeling for real-world agricultural use cases, with an emphasis on scalable architecture and reliable model performance.`,

  education: [
    {
      degree: "B.Tech in CSBS",
      institution: "RAIT (Ramrao Adik Institute of Technology)",
      year: "Current Programme",
      gpa: "7.32 / 10 (Semester 5)",
      note: "CGPA improved from approximately 4.39 in early semesters to 7.32 by Semester 5.",
    },
  ],

  research: [
    {
      title: "Crop Recommendation System using XGBoost & Random Forest",
      synopsis: "A machine learning solution leveraging XGBoost and Random Forest to empower farmers with data-driven crop selection. Optimized for high-accuracy predictions using environmental and soil NPK parameters.",
      status: "Research Spotlight",
      venue: "Applied ML Project",
      tags: ["Python", "Scikit-Learn", "XGBoost", "Random Forest"],
      year: "2026",
      description: "Developed a predictive model to suggest optimal crops based on soil NPK levels and weather parameters. Focused on modular OOP architecture for scalability.",
    },
    {
      title: "Portfolio Website using GenAI Agents & Tools",
      synopsis: "Designed and built this portfolio website using GenAI agents and tools to accelerate content structuring, UI refinement, and iterative development workflows while maintaining manual review over final output quality.",
      status: "Project",
      venue: "Personal Project",
      tags: ["React", "Tailwind CSS", "GenAI Agents", "Developer Tools"],
      year: "2026",
      description: "Built a responsive professional portfolio with an editorial-academic design system and data-driven section architecture.",
    },
  ],

  certification: {
    title: "Data Science & GenAI Professional Certification",
    issuer: "iHUB DivyaSampark, IIT Roorkee",
    status: "In Progress / Specialized Training",
  },

  skills: {
    "Languages & ML": ["Python", "R", "SQL", "PyTorch", "HuggingFace Transformers", "spaCy"],
    "Methods": ["NLP", "Causal Inference", "Network Analysis", "Bayesian Modelling", "BERTopic"],
    "Tools": ["Git", "Docker", "Weights & Biases", "Streamlit", "LaTeX", "Notion"],
    "Domain": ["Computational Social Science", "Policy Analytics", "Media Studies"],
  },

  aiTransparency: {
    intro: "This portfolio was designed and developed with substantive assistance from Claude (Anthropic). Below is an honest account of how AI participated in this project — including what it did well and where human judgement was irreplaceable.",
    sections: [
      {
        icon: "code",
        title: "Architecture & Code Generation",
        detail: "The headless data/UI separation was conceived by me but the scaffold — component hierarchy, sidebar layout, responsive breakpoints — was generated by Claude Sonnet 4.6 in a single prompt. I reviewed and refactored the output for correctness and style consistency.",
        aiContribution: 85,
        humanContribution: 15,
      },
      {
        icon: "layers",
        title: "Design System & Aesthetics",
        detail: "I specified the 'editorial academic' aesthetic direction: cream palette, serif/mono pairing, thin geometric rules. Claude translated this direction into Tailwind utility classes. The final typographic scale and spacing rhythm required several rounds of human iteration.",
        aiContribution: 60,
        humanContribution: 40,
      },
      {
        icon: "bot",
        title: "Research Abstracts",
        detail: "All research content — methodologies, findings, claims — is written by me from my actual work. Claude was used only for copy-editing grammatical consistency and tightening verbose phrasing. No factual content was AI-generated.",
        aiContribution: 10,
        humanContribution: 90,
      },
      {
        icon: "bar-chart",
        title: "Bias & Limitations",
        detail: "AI-assisted code can carry subtle biases in design choices (e.g. defaulting to common layout patterns). I manually audited accessibility, colour contrast, and mobile layout. Readers should critically evaluate any AI-assisted artifact rather than treating polish as a proxy for quality.",
        aiContribution: 0,
        humanContribution: 100,
      },
    ],
  },
};

// ─── CONSTANTS ────────────────────────────────────────────────────────────────
const NAV_ITEMS = [
  { id: "about",    label: "About",          icon: BookOpen },
  { id: "research", label: "Research Spotlight", icon: FileText },
  { id: "certification", label: "Certification", icon: Award },
  { id: "stats",    label: "Metrics",         icon: BarChart2 },
  { id: "skills",   label: "Skills",          icon: Layers },
  { id: "ai",       label: "AI Transparency", icon: Bot },
];

const STATUS_STYLE = {
  "Research Spotlight": "bg-sky-50 text-sky-700 border-sky-200",
  "Project": "bg-indigo-50 text-indigo-700 border-indigo-200",
  "Published":    "bg-emerald-50 text-emerald-700 border-emerald-200",
  "Under Review": "bg-amber-50  text-amber-700  border-amber-200",
  "Working Paper":"bg-slate-50  text-slate-600  border-slate-200",
};

// ─── HELPERS ─────────────────────────────────────────────────────────────────
function useActiveSection() {
  const [active, setActive] = useState("about");
  useEffect(() => {
    const ids = NAV_ITEMS.map((n) => n.id);
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => { if (e.isIntersecting) setActive(e.target.id); });
      },
      { rootMargin: "-40% 0px -55% 0px" }
    );
    ids.forEach((id) => { const el = document.getElementById(id); if (el) observer.observe(el); });
    return () => observer.disconnect();
  }, []);
  return [active, setActive];
}

function scrollTo(id, setActive, closeMobile) {
  const el = document.getElementById(id);
  if (el) { el.scrollIntoView({ behavior: "smooth", block: "start" }); setActive(id); }
  if (closeMobile) closeMobile();
}

// ─── MINI COMPONENTS ─────────────────────────────────────────────────────────

function Tag({ children }) {
  return (
    <span className="inline-block text-xs font-mono tracking-wide px-2 py-0.5 border border-stone-300 text-stone-500 rounded-sm">
      {children}
    </span>
  );
}

function SectionTitle({ children }) {
  return (
    <div className="mb-8">
      <h2 className="font-serif text-2xl text-stone-800 tracking-tight">{children}</h2>
      <div className="mt-2 h-px w-12 bg-stone-400" />
    </div>
  );
}

function ContributionBar({ ai, human }) {
  return (
    <div className="mt-3">
      <div className="flex justify-between text-xs font-mono text-stone-400 mb-1">
        <span>Human {human}%</span>
        <span>AI {ai}%</span>
      </div>
      <div className="h-1 w-full bg-stone-200 rounded-full overflow-hidden flex">
        <div className="h-full bg-stone-600 transition-all duration-700" style={{ width: `${human}%` }} />
        <div className="h-full bg-amber-400" style={{ width: `${ai}%` }} />
      </div>
    </div>
  );
}

// ─── SIDEBAR ─────────────────────────────────────────────────────────────────
function Sidebar({ active, setActive, mobile, onClose }) {
  const base = mobile
    ? "fixed inset-0 z-50 flex"
    : "hidden lg:flex flex-col w-64 xl:w-72 min-h-screen sticky top-0 border-r border-slate-700 bg-slate-900";

  if (mobile) {
    return (
      <div className="fixed inset-0 z-50 flex">
        <div className="absolute inset-0 bg-stone-900/40 backdrop-blur-sm" onClick={onClose} />
        <div className="relative flex flex-col w-72 min-h-screen bg-slate-900 border-r border-slate-700 p-8 shadow-2xl">
          <button
            onClick={onClose}
            aria-label="Close menu"
            className="absolute right-4 top-4 rounded p-1 text-slate-300 hover:bg-slate-800 hover:text-white"
          >
            <X size={16} />
          </button>
          <SidebarContent active={active} setActive={setActive} onClose={onClose} />
        </div>
      </div>
    );
  }

  return (
    <aside className={base}>
      <div className="flex flex-col h-full p-8">
        <SidebarContent active={active} setActive={setActive} />
      </div>
    </aside>
  );
}

function SidebarContent({ active, setActive, onClose }) {
  const d = DATA.meta;
  return (
    <>
      {/* Identity */}
      <div className="mb-10">
        <div className="w-12 h-12 rounded-full bg-slate-200 flex items-center justify-center mb-4">
          <span className="font-serif text-xl text-slate-900">
            {d.name.split(" ").map((w) => w[0]).join("")}
          </span>
        </div>
        <p className="font-serif text-lg text-slate-100 leading-snug">{d.name}</p>
        <p className="text-xs text-slate-300 mt-1 font-mono">{d.affiliation}</p>
        <p className="text-xs text-slate-400 mt-2 leading-relaxed">{d.tagline}</p>
      </div>

      {/* Nav */}
      <nav className="flex-1">
        <ul className="space-y-1">
          {NAV_ITEMS.map(({ id, label, icon: Icon }) => {
            const isActive = active === id;
            return (
              <li key={id}>
                <button
                  onClick={() => scrollTo(id, setActive, onClose)}
                  className={`w-full flex items-center gap-3 px-3 py-2 rounded text-sm transition-all duration-150 group
                    ${isActive
                      ? "bg-slate-100 text-slate-900"
                      : "text-slate-300 hover:text-white hover:bg-slate-800"}`}
                >
                  <Icon size={14} className="flex-shrink-0" />
                  <span className="font-medium tracking-wide">{label}</span>
                  {isActive && <ChevronRight size={12} className="ml-auto" />}
                </button>
              </li>
            );
          })}
        </ul>
      </nav>

      {/* Contact */}
      <div className="mt-auto pt-8 border-t border-slate-700">
        <div className="space-y-2">
          {[
            { href: `mailto:${d.email}`, icon: Mail, label: d.email },
            { href: `https://${d.github}`, icon: ExternalLink, label: "GitHub" },
            { href: `https://${d.linkedin}`, icon: ExternalLink, label: "LinkedIn" },
          ].map(({ href, icon: Icon, label }) => (
            <a key={label} href={href} target="_blank" rel="noreferrer"
              className="flex items-center gap-2 text-xs text-slate-400 hover:text-slate-100 transition-colors group">
              <Icon size={12} />
              <span className="truncate">{label}</span>
            </a>
          ))}
        </div>
        <a href={d.cvUrl} target="_blank" rel="noreferrer"
          className="mt-4 flex items-center gap-2 text-xs font-mono text-slate-200 hover:text-white border border-slate-500 hover:border-slate-300 px-3 py-2 rounded transition-all">
          <Download size={12} />
          Download CV
        </a>
      </div>
    </>
  );
}

// ─── SECTIONS ────────────────────────────────────────────────────────────────

function AboutSection() {
  const d = DATA;
  return (
    <section id="about" className="mb-20 scroll-mt-8">
      <SectionTitle>About</SectionTitle>
      <p className="text-stone-600 leading-relaxed text-base max-w-2xl mb-10">{d.about}</p>

      <h3 className="font-serif text-lg text-stone-700 mb-5">Education</h3>
      <div className="space-y-4">
        {d.education.map((e) => (
          <div key={e.degree} className="flex gap-5 p-5 border border-stone-200 rounded-lg bg-white">
            <GraduationCap size={18} className="text-stone-400 mt-0.5 flex-shrink-0" />
            <div className="flex-1 min-w-0">
              <div className="flex items-start justify-between gap-4 flex-wrap">
                <div>
                  <p className="font-medium text-stone-800 text-sm">{e.degree}</p>
                  <p className="text-stone-500 text-sm">{e.institution}</p>
                  <p className="text-stone-400 text-xs mt-1">{e.note}</p>
                </div>
                <div className="text-right flex-shrink-0">
                  <p className="font-mono text-xs text-stone-500">{e.year}</p>
                  <p className="font-mono text-sm font-medium text-stone-700 mt-1">{e.gpa}</p>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function ResearchSection() {
  const [expanded, setExpanded] = useState(null);
  return (
    <section id="research" className="mb-20 scroll-mt-8">
      <SectionTitle>Research Spotlight</SectionTitle>
      <div className="space-y-4">
        {DATA.research.map((r, i) => {
          const open = expanded === i;
          return (
            <div key={i}
              className={`border rounded-lg bg-white transition-all duration-200 ${open ? "border-stone-400" : "border-stone-200"}`}>
              <button
                className="w-full text-left p-5"
                onClick={() => setExpanded(open ? null : i)}>
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-2 flex-wrap">
                      <span className={`text-xs px-2 py-0.5 rounded border font-mono ${STATUS_STYLE[r.status] ?? STATUS_STYLE["Working Paper"]}`}>
                        {r.status}
                      </span>
                      <span className="font-mono text-xs text-stone-400">{r.year}</span>
                      {r.venue !== "—" && (
                        <span className="font-mono text-xs text-stone-400">{r.venue}</span>
                      )}
                    </div>
                    <p className="font-serif text-base text-stone-800 leading-snug">{r.title}</p>
                    {"description" in r && (
                      <p className="mt-2 text-sm text-stone-600 leading-relaxed">{r.description}</p>
                    )}
                  </div>
                  <ChevronRight
                    size={16}
                    className={`text-stone-400 flex-shrink-0 mt-1 transition-transform duration-200 ${open ? "rotate-90" : ""}`} />
                </div>
                <div className="flex gap-2 mt-3 flex-wrap">
                  {r.tags.map((t) => <Tag key={t}>{t}</Tag>)}
                </div>
              </button>
              {open && (
                <div className="px-5 pb-5 border-t border-stone-100 pt-4">
                  <p className="text-sm text-stone-600 leading-relaxed">{r.synopsis}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

function StatsSection() {
  return (
    <section id="stats" className="mb-20 scroll-mt-8">
      <SectionTitle>Metrics</SectionTitle>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {DATA.stats.map((s) => (
          <div key={s.label} className="border border-stone-200 bg-white rounded-lg p-5">
            <p className="text-xs text-stone-400 font-mono tracking-wider uppercase mb-2">{s.label}</p>
            <p className="font-serif text-3xl text-stone-800">
              {s.value}
              <span className="text-lg text-stone-400">{s.suffix}</span>
            </p>
            <p className="text-xs text-stone-400 mt-2">{s.note}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

function CertificationSection() {
  const cert = DATA.certification;
  return (
    <section id="certification" className="mb-20 scroll-mt-8">
      <SectionTitle>Certification</SectionTitle>
      <div className="border border-amber-300 bg-amber-50 rounded-lg p-6 shadow-sm">
        <div className="flex items-start gap-3">
          <Award size={18} className="text-amber-700 mt-0.5 flex-shrink-0" />
          <div className="min-w-0">
            <p className="font-serif text-lg text-stone-800">{cert.title}</p>
            <p className="text-sm text-stone-600 mt-1">{cert.issuer}</p>
            <p className="inline-block mt-3 text-xs font-mono px-2 py-1 rounded border border-amber-300 text-amber-800 bg-white">
              {cert.status}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

function SkillsSection() {
  return (
    <section id="skills" className="mb-20 scroll-mt-8">
      <SectionTitle>Skills</SectionTitle>
      <div className="grid sm:grid-cols-2 gap-6">
        {Object.entries(DATA.skills).map(([category, items]) => (
          <div key={category} className="border border-stone-200 bg-white rounded-lg p-5">
            <p className="text-xs font-mono tracking-wider text-stone-400 uppercase mb-3">{category}</p>
            <div className="flex flex-wrap gap-2">
              {items.map((item) => (
                <span key={item}
                  className="text-sm text-stone-700 bg-stone-50 border border-stone-200 px-2.5 py-1 rounded">
                  {item}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function AITransparencySection() {
  const ai = DATA.aiTransparency;
  const iconMap = { code: Code2, layers: Layers, bot: Bot, "bar-chart": BarChart2 };
  return (
    <section id="ai" className="mb-20 scroll-mt-8">
      <SectionTitle>AI Transparency</SectionTitle>

      {/* Banner */}
      <div className="mb-8 p-5 bg-amber-50 border border-amber-200 rounded-lg">
        <div className="flex items-start gap-3">
          <Bot size={16} className="text-amber-600 mt-0.5 flex-shrink-0" />
          <p className="text-sm text-amber-800 leading-relaxed">{ai.intro}</p>
        </div>
      </div>

      {/* Cards */}
      <div className="grid sm:grid-cols-2 gap-5">
        {ai.sections.map((s) => {
          const Icon = iconMap[s.icon] ?? Bot;
          return (
            <div key={s.title} className="border border-stone-200 bg-white rounded-lg p-5">
              <div className="flex items-center gap-2 mb-3">
                <Icon size={14} className="text-stone-500" />
                <p className="font-medium text-stone-800 text-sm">{s.title}</p>
              </div>
              <p className="text-xs text-stone-500 leading-relaxed">{s.detail}</p>
              <ContributionBar ai={s.aiContribution} human={s.humanContribution} />
            </div>
          );
        })}
      </div>

      {/* Methodology note */}
      <div className="mt-6 p-4 border-l-2 border-stone-300 bg-stone-50 rounded-r-lg">
        <p className="text-xs text-stone-500 leading-relaxed">
          <span className="font-medium text-stone-600">Methodology note:</span> Contribution estimates are the author's own qualitative assessment, not automatically generated metrics. Legend: <span className="font-mono text-stone-700">■</span> Human &nbsp; <span className="font-mono text-amber-500">■</span> AI-assisted.
        </p>
      </div>
    </section>
  );
}

// ─── APP ─────────────────────────────────────────────────────────────────────
function App() {
  const [active, setActive] = useActiveSection();
  const [mobileOpen, setMobileOpen] = useState(false);

  return (
    <div className="min-h-screen bg-[#fdfcf7] font-sans">
      {/* Import serif font */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600&family=JetBrains+Mono:wght@400;500&family=Inter:wght@400;500&display=swap');
        .font-serif { font-family: 'Playfair Display', Georgia, serif; }
        .font-mono  { font-family: 'JetBrains Mono', monospace; }
        .font-sans  { font-family: 'Inter', system-ui, sans-serif; }
        html { scroll-behavior: smooth; }
      `}</style>

      {/* Mobile topbar */}
      <div className="lg:hidden fixed top-0 left-0 right-0 z-40 bg-[#fdfcf7]/90 backdrop-blur border-b border-stone-200 px-5 py-3 flex items-center justify-between">
        <div>
          <p className="font-serif text-sm text-stone-800">{DATA.meta.name}</p>
          <p className="text-xs text-stone-400 font-mono">{DATA.meta.affiliation}</p>
        </div>
        <button onClick={() => setMobileOpen(true)} className="p-1.5 rounded hover:bg-stone-100 transition-colors">
          <Menu size={18} className="text-stone-600" />
        </button>
      </div>

      {/* Mobile sidebar */}
      {mobileOpen && (
        <Sidebar mobile active={active} setActive={setActive} onClose={() => setMobileOpen(false)} />
      )}

      <div className="flex">
        {/* Desktop sidebar */}
        <Sidebar active={active} setActive={setActive} />

        {/* Main content */}
        <main className="flex-1 min-w-0 px-6 sm:px-10 lg:px-14 xl:px-20 py-12 lg:py-16 pt-20 lg:pt-16">
          <div className="max-w-2xl">
            <AboutSection />
            <ResearchSection />
            <CertificationSection />
            <StatsSection />
            <SkillsSection />
            <AITransparencySection />

            {/* Footer */}
            <footer className="border-t border-stone-200 pt-8 pb-4">
              <p className="text-xs text-stone-400 font-mono">
                © {new Date().getFullYear()} {DATA.meta.name} · Built with React + Tailwind · Data in{" "}
                <code className="bg-stone-100 px-1 rounded">data.json</code>
              </p>
            </footer>
          </div>
        </main>
      </div>
    </div>
  );
}

export default App;